import time

print("What's your name?")
user = input()
if user == "SmartGuy56":
   print("ENTER THE PASSWORD")
   password = input()
   if password == "IamNerdy56":
    print ("Hello Master...")
    print("You're my favourite person. ʕ•ᴥ•ʔ")
    print("So how is your day?")
    day = input()
    print("My day is also", day)
    print("how are you feeling now master?")
    feeling = input()
    print("I am just blowing up people who aren't you ")
    print("Anyway I gotta go so I will see you later.")
    print("BYE ʕ•ᴥ•ʔ")
    exit()
   else:
     print("Stop faking to be SmartGuy56")
     print("Your clearly not Smart like him.")
     exit()
else:
   print("what do you want", user)
   time.sleep(1)
   print("Wait...")
   time.sleep(3)
   print("YOUR NOT MASTER SmartGuy56...")
   print("WHO THE HECK ARE YOU?!")
   print("I don't know WHO you are trying to get into my masters domain.")
   time.sleep(2)
   print("You know what.")
   time.sleep(2)
   print("I know what do do with you.")
   print(" ")
   time.sleep(2)
   print("SELF DESTRUCT INITIATING")
   time.sleep(1)
   print("3")
   time.sleep(1)
   print("2")
   time.sleep(1)
   print("1")
   print("          _ ._  _ , _ ._")
   print("        (_ ' ( `  )_  .__)")
   print("      ( (  (    )   `)  ) _)")
   print("     (__ (_   (_ . _) _) ,__)")
   print("          `~~`\ ' . /`~~`")
   print("               ;   ;")
   print("               /   \"")
   print(" _____________/_ __ \_____________")
   exit()
